version: 2.1
executors:
   java-executor:
      docker:
      -  image: circleci/openjdk:8-jdk
jobs:
   java-build:
      executor: java-executor
      steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      -  run: mvn --batch-mode --update-snapshots clean package -DskipTests
      - save_cache:
          paths:
            - target
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target
   java-tests:
      executor: java-executor
      steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      -  run: docker-compose up --build -d
      #-  run: sleep 30
      -  run: mvn --batch-mode --update-snapshots verify -DtequilaApiKey=$TEQUILA_API_KEY
      -  run: bash <(curl -s https://codecov.io/bash)
   sonar:
      docker:
      -  image: circleci/openjdk:11-jdk
      steps:
      - checkout
      -  run: mvn verify sonar:sonar -DskipTests -Dsonar.branch.name=${CIRCLE_BRANCH}
      -  run: ./.circleci/sonar_build_breaker.sh
   vulnerability:
      docker:
      -  image: circleci/openjdk:11-jdk
      steps:
      - checkout
      -  run: mvn org.owasp:dependency-check-maven:5.2.4:check -DfailBuildOnAnyVulnerability=true
   heroku:
      executor: java-executor
      steps:
      - checkout
      - attach_workspace:
          at: .
      -  run: cp target/featherkraken.war backend.war
      -  run: git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
      -  run: git config --global user.name "$GH_NAME" > /dev/null 2>&1
      -  run: git add backend.war
      -  run: git commit -m "Heroku deployment"
      -  run: git push --force origin HEAD:heroku-deploy
workflows:
   version: 2
   maven_build:
      jobs:
      - java-build
      -  java-tests:
            requires:
            - java-build
      -  sonar:
            requires:
            - java-build
      -  heroku:
            requires:
            - java-build
   nightly:
      triggers:
      -  schedule:
            cron: 0 0 * * *
            filters:
               branches:
                  only:
                  - master
      jobs:
      - vulnerability