name: "Tests"
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build project to package
        run: mvn --batch-mode --update-snapshots clean package -DskipTests
      - name: Start docker containers
        run: docker-compose up --build -d
      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify
        env:
          TEQUILA_API_KEY: $TEQUILA_API_KEY
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
